create table posts (
    post_id bigint generated by default as identity, 
    auth_id int references app_users,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    content text check (char_length(content) < 300),
    is_lie boolean,
    is_active boolean,

    primary key (post_id)
);


INSERT INTO posts (auth_id, created_at, updated_at, content, is_lie, is_active)
VALUES
    (1, now(), now(), 'This is the content of post 1.', false, true),
    (2, now(), now(), 'This is the content of post 2.', true, true),
    (3, now(), now(), 'This is the content of post 3.', false, true),
    (4, now(), now(), 'This is the content of post 4.', false, true),
    (5, now(), now(), 'This is the content of post 5.', true, true),
    (6, now(), now(), 'This is the content of post 6.', false, true),
    (7, now(), now(), 'This is the content of post 7.', true, true),
    (8, now(), now(), 'This is the content of post 8.', false, true),
    (9, now(), now(), 'This is the content of post 9.', false, true),
    (10, now(), now(), 'This is the content of post 10.', true, true);
