create table comments (
    comment_id bigint generated by default as identity, 
    replying_post_id bigint references posts,
    replying_comment_id bigint references comments,
    auth_id uuid references auth.users default auth.uid() not null,
    updated_at timestamp with time zone,
    created_at timestamp with time zone,
    content text check (char_length(content) < 300),
    is_active boolean,

    primary key (comment_id)
);

alter table comments enable row level security;

create policy "Public comments are viewable by everyone." on 
comments for
    select using (true);

create policy "Individuals can create comments." on 
comments for
    insert with check (auth.uid() = auth_id);

create policy "Individuals can update their own comments." on 
comments for
    update using (auth.uid() = auth_id);

create policy "Individuals can delete their own comments." on 
comments for
    delete using (auth.uid() = auth_id);